export { default as SideMenu } from "./SideMenu/SideMenu"
export { default as GlobalStat } from "./GlobalStat/GlobalStat"
export { default as TopCrypto } from "./TopCrypto/TopCrypto"
export { default as News } from "./News/News"
export { default as DetailCurrency } from "./DetailCurrency/DetailCurrency"
export { default as LineChart } from "./LineChart/LineChart"
